import os
import re
import sys
import json
from datetime import date, timedelta

import anthropic
from pydantic import BaseModel

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from models import AgentState, HireEmployeeParams
from data_loader import _load


# ─────────────────────────────────────────
# OUTPUT SCHEMAS
# ─────────────────────────────────────────

class DraftJDOutput(BaseModel):
    job_description: str
    required_skills: list[str]
    nice_to_have_skills: list[str]
    experience_years: int
    job_type: str
    location: str


class CandidateResult(BaseModel):
    name: str
    matched_skills: list[str]
    unmatched_skills: list[str]
    match_score: float


class ShortlistOutput(BaseModel):
    shortlisted: list[CandidateResult]
    rejected: list[CandidateResult]
    shortlist_threshold_used: float


class InterviewSlot(BaseModel):
    candidate: str
    round: int
    suggested_date: str             # YYYY-MM-DD
    duration_mins: int


class ScheduleInterviewOutput(BaseModel):
    interview_plan: list[InterviewSlot]


class OfferLetterOutput(BaseModel):
    candidate_name: str
    role: str
    department: str
    job_type: str
    location: str
    offer_letter: str               # Full offer letter text generated by Claude


class RecruitmentAgentOutput(BaseModel):
    task_id: str
    action: str
    # "completed" | "failed" | "needs_approval"
    # Agent sets this. Orchestrator (Person 1) reads it and decides
    # whether to pause the graph. Agent never touches state.status directly.
    status: str
    result: (
        DraftJDOutput
        | ShortlistOutput
        | ScheduleInterviewOutput
        | OfferLetterOutput
    )


# ─────────────────────────────────────────
# LLM CLIENT
# ─────────────────────────────────────────

client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
MODEL  = "claude-sonnet-4-20250514"


def _call_claude(system_prompt: str, user_prompt: str) -> str:
    response = client.messages.create(
        model=MODEL,
        max_tokens=1000,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )
    return response.content[0].text


def _parse_json(raw: str) -> dict:
    """
    Strips markdown code fences robustly then parses JSON.
    Handles: plain JSON, ```json ... ```, ``` ... ```, leading/trailing whitespace.
    """
    cleaned = re.sub(r"^```(?:json)?\s*", "", raw.strip(), flags=re.IGNORECASE)
    cleaned = re.sub(r"\s*```$", "", cleaned.strip())
    return json.loads(cleaned.strip())


def _get_current_task(state: AgentState):
    for task in state.tasks:
        if task.task_id == state.current_task_id:
            return task
    raise ValueError(f"Task '{state.current_task_id}' not found in state.tasks")


# ─────────────────────────────────────────
# ACTION 1 — DRAFT JD
# Uses Claude to write the job description.
# No human approval needed — internal document.
# ─────────────────────────────────────────

def draft_jd(state: AgentState) -> AgentState:
    """
    Reads:  state.params → role, department, experience_years,
                           skills_required, job_type, location
    Writes: state.outputs[task_id] → RecruitmentAgentOutput(DraftJDOutput)
            state.completed_tasks
    """
    task   = _get_current_task(state)
    params = state.params

    if not isinstance(params, HireEmployeeParams):
        raise ValueError("draft_jd requires HireEmployeeParams")

    system_prompt = """
You are a professional HR recruitment specialist.
Your job is to write clear, attractive job descriptions for open positions.
You must respond ONLY with a valid JSON object — no explanation, no markdown, no preamble.
The JSON must exactly match this structure:
{
  "job_description": "<full JD as a string>",
  "required_skills": ["skill1", "skill2"],
  "nice_to_have_skills": ["skill1", "skill2"],
  "experience_years": <integer>,
  "job_type": "<full_time|part_time|contract>",
  "location": "<city or Remote>"
}
"""

    user_prompt = f"""
Write a job description for the following position:

Role: {params.role}
Department: {params.department}
Experience Required: {params.experience_years} years
Required Skills: {', '.join(params.skills_required)}
Job Type: {params.job_type}
Location: {params.location}

Generate 3-5 nice-to-have skills that complement the required skills.
Keep the job description professional, concise, and appealing to candidates.
"""

    raw    = _call_claude(system_prompt, user_prompt)
    parsed = _parse_json(raw)
    result = DraftJDOutput(**parsed)

    output = RecruitmentAgentOutput(
        task_id=task.task_id,
        action="draft_jd",
        status="completed",
        result=result,
    )

    state.outputs[task.task_id] = output.model_dump()
    state.completed_tasks.append(task.task_id)
    return state


# ─────────────────────────────────────────
# ACTION 2 — SHORTLIST CANDIDATES
# Pure Python — no Claude needed.
# Sets status="needs_approval" so Person 1
# knows to pause and show Person 4's interrupt
# screen before scheduling interviews.
# ─────────────────────────────────────────

SHORTLIST_THRESHOLD = 0.60


def shortlist_candidates(state: AgentState) -> AgentState:
    """
    Reads:  state.params → role, skills_required
            state.outputs[t1] → required_skills from draft_jd (fallback: params)
    Writes: state.outputs[task_id] → RecruitmentAgentOutput(ShortlistOutput)
            state.completed_tasks

    Note on status="needs_approval":
        The agent sets this on the OUTPUT object only.
        It is Person 1's orchestrator responsibility to read this flag
        and set state.status = "paused". The agent never writes state.status.

    Logic:
        - Loads candidates.json filtered by role
        - match_score = matched_skills / total_required_skills
        - score >= SHORTLIST_THRESHOLD → shortlisted, else rejected
        - Shortlisted sorted by score descending
    """
    task   = _get_current_task(state)
    params = state.params

    if not isinstance(params, HireEmployeeParams):
        raise ValueError("shortlist_candidates requires HireEmployeeParams")

    # Read required_skills from draft_jd output if available, else fall back to params
    prev_task_id    = task.depends_on[0]
    prev_raw        = state.outputs.get(prev_task_id, {})
    required_skills = (
        prev_raw.get("result", {}).get("required_skills")
        or params.skills_required
    )

    # Load and filter candidates by role
    all_candidates  = _load("candidates.json")
    role_candidates = [
        c for c in all_candidates
        if c["role_applied"].lower() == params.role.lower()
    ]

    if not role_candidates:
        output = RecruitmentAgentOutput(
            task_id=task.task_id,
            action="shortlist_candidates",
            status="failed",
            result=ShortlistOutput(
                shortlisted=[],
                rejected=[],
                shortlist_threshold_used=SHORTLIST_THRESHOLD,
            ),
        )
        state.outputs[task.task_id] = output.model_dump()
        state.completed_tasks.append(task.task_id)
        return state

    shortlisted = []
    rejected    = []

    for candidate in role_candidates:
        candidate_skills = [s.lower() for s in candidate["skills"]]
        matched   = [s for s in required_skills if s.lower() in candidate_skills]
        unmatched = [s for s in required_skills if s.lower() not in candidate_skills]
        score     = round(len(matched) / len(required_skills), 2) if required_skills else 0.0

        entry = CandidateResult(
            name=candidate["name"],
            matched_skills=matched,
            unmatched_skills=unmatched,
            match_score=score,
        )
        (shortlisted if score >= SHORTLIST_THRESHOLD else rejected).append(entry)

    shortlisted.sort(key=lambda c: c.match_score, reverse=True)

    result = ShortlistOutput(
        shortlisted=shortlisted,
        rejected=rejected,
        shortlist_threshold_used=SHORTLIST_THRESHOLD,
    )

    # status="needs_approval": Person 1 reads this and decides to pause.
    # This agent does NOT write state.status = "paused".
    output = RecruitmentAgentOutput(
        task_id=task.task_id,
        action="shortlist_candidates",
        status="needs_approval",
        result=result,
    )

    state.outputs[task.task_id] = output.model_dump()
    state.completed_tasks.append(task.task_id)
    return state


# ─────────────────────────────────────────
# ACTION 3 — SCHEDULE INTERVIEW
# Pure Python — no Claude needed.
# ─────────────────────────────────────────

ROUND_CONFIG = [
    {"round": 1, "label": "Technical Screen", "duration_mins": 45},
    {"round": 2, "label": "Culture Fit",       "duration_mins": 30},
]
MAX_INTERVIEWS_PER_DAY = 3


def _next_working_day(d: date) -> date:
    """Returns the next Monday–Friday date strictly after d."""
    d += timedelta(days=1)
    while d.weekday() >= 5:
        d += timedelta(days=1)
    return d


def schedule_interview(state: AgentState) -> AgentState:
    """
    Reads:  state.outputs[t2] → shortlisted candidates from shortlist_candidates
    Writes: state.outputs[task_id] → RecruitmentAgentOutput(ScheduleInterviewOutput)
            state.completed_tasks

    Logic:
        - 2 rounds per candidate (technical + culture fit)
        - Starts one week from today, working days only (Mon–Fri)
        - Max MAX_INTERVIEWS_PER_DAY per day
    """
    task   = _get_current_task(state)
    params = state.params

    if not isinstance(params, HireEmployeeParams):
        raise ValueError("schedule_interview requires HireEmployeeParams")

    # Deserialize previous output properly to catch schema changes early
    prev_task_id = task.depends_on[0]
    prev_raw     = state.outputs.get(prev_task_id, {})

    try:
        prev_output  = RecruitmentAgentOutput(**prev_raw)
        shortlist    = ShortlistOutput.model_validate(prev_output.result)
        shortlisted  = shortlist.shortlisted
    except Exception:
        # Graceful fallback: read as plain dict
        shortlisted_raw = prev_raw.get("result", {}).get("shortlisted", [])
        shortlisted = [CandidateResult(**c) for c in shortlisted_raw]

    if not shortlisted:
        output = RecruitmentAgentOutput(
            task_id=task.task_id,
            action="schedule_interview",
            status="failed",
            result=ScheduleInterviewOutput(interview_plan=[]),
        )
        state.outputs[task.task_id] = output.model_dump()
        state.completed_tasks.append(task.task_id)
        return state

    # Start one week from today on a working day
    current_day       = date.today() + timedelta(weeks=1)
    while current_day.weekday() >= 5:
        current_day = _next_working_day(current_day)

    interviews_on_day = 0
    interview_plan    = []

    for candidate in shortlisted:
        for round_cfg in ROUND_CONFIG:
            if interviews_on_day >= MAX_INTERVIEWS_PER_DAY:
                current_day       = _next_working_day(current_day)
                interviews_on_day = 0

            interview_plan.append(InterviewSlot(
                candidate=candidate.name,
                round=round_cfg["round"],
                suggested_date=current_day.strftime("%Y-%m-%d"),
                duration_mins=round_cfg["duration_mins"],
            ))
            interviews_on_day += 1

    result = ScheduleInterviewOutput(interview_plan=interview_plan)

    output = RecruitmentAgentOutput(
        task_id=task.task_id,
        action="schedule_interview",
        status="completed",
        result=result,
    )

    state.outputs[task.task_id] = output.model_dump()
    state.completed_tasks.append(task.task_id)
    return state


# ─────────────────────────────────────────
# ACTION 4 — SEND OFFER
# Uses Claude to generate the offer letter.
# Sets status="needs_approval" — this is
# irreversible (goes to a real candidate),
# so Person 1 must pause for manager sign-off.
# ─────────────────────────────────────────

def send_offer(state: AgentState) -> AgentState:
    """
    Reads:  state.params → role, department, job_type, location
            state.outputs[t2] → top shortlisted candidate name
    Writes: state.outputs[task_id] → RecruitmentAgentOutput(OfferLetterOutput)
            state.completed_tasks

    Note on status="needs_approval":
        Offer letters go to real candidates — irreversible action.
        Person 1's orchestrator must pause and show Person 4's interrupt
        screen before this is actually sent.
    """
    task   = _get_current_task(state)
    params = state.params

    if not isinstance(params, HireEmployeeParams):
        raise ValueError("send_offer requires HireEmployeeParams")

    # Get top candidate from shortlist output (t2)
    shortlist_task_id  = task.depends_on[0]
    shortlist_raw      = state.outputs.get(shortlist_task_id, {})
    shortlisted        = shortlist_raw.get("result", {}).get("shortlisted", [])

    if not shortlisted:
        output = RecruitmentAgentOutput(
            task_id=task.task_id,
            action="send_offer",
            status="failed",
            result=OfferLetterOutput(
                candidate_name="N/A",
                role=params.role,
                department=params.department,
                job_type=params.job_type,
                location=params.location,
                offer_letter="No shortlisted candidates available.",
            ),
        )
        state.outputs[task.task_id] = output.model_dump()
        state.completed_tasks.append(task.task_id)
        return state

    # Pick the top-scored candidate
    top_candidate = shortlisted[0]["name"] if isinstance(shortlisted[0], dict) else shortlisted[0].name

    system_prompt = """
You are a professional HR specialist drafting formal job offer letters.
You must respond ONLY with a valid JSON object — no explanation, no markdown, no preamble.
The JSON must exactly match this structure:
{
  "candidate_name": "<full name>",
  "role": "<role title>",
  "department": "<department>",
  "job_type": "<full_time|part_time|contract>",
  "location": "<city or Remote>",
  "offer_letter": "<full formal offer letter as a string>"
}
"""

    user_prompt = f"""
Draft a formal job offer letter for the following:

Candidate Name: {top_candidate}
Role: {params.role}
Department: {params.department}
Job Type: {params.job_type}
Location: {params.location}
Company: Acme Corp

The letter should:
- Congratulate the candidate warmly
- Clearly state the role, department, and location
- Mention the job type (full-time / part-time / contract)
- Ask them to confirm acceptance within 5 business days
- Be signed off by "The HR Team, Acme Corp"
Keep it professional and concise — one page maximum.
"""

    raw    = _call_claude(system_prompt, user_prompt)
    parsed = _parse_json(raw)
    result = OfferLetterOutput(**parsed)

    # status="needs_approval": orchestrator must pause — offer is irreversible
    output = RecruitmentAgentOutput(
        task_id=task.task_id,
        action="send_offer",
        status="needs_approval",
        result=result,
    )

    state.outputs[task.task_id] = output.model_dump()
    state.completed_tasks.append(task.task_id)
    return state


# ─────────────────────────────────────────
# DISPATCHER — single entry point for Person 1
#
# Person 1's orchestrator calls ONLY this function.
# It reads state.current_task_id → finds the task →
# reads task.action → routes to the right function.
# ─────────────────────────────────────────

ACTION_MAP = {
    "draft_jd":             draft_jd,
    "shortlist_candidates": shortlist_candidates,
    "schedule_interview":   schedule_interview,
    "send_offer":           send_offer,
}


def run_recruitment_agent(state: AgentState) -> AgentState:
    """
    Main entry point. Person 1 calls this function.

    Reads state.current_task_id to find the current task,
    then dispatches to the correct action function.

    Args:
        state: The shared AgentState from the LangGraph graph.

    Returns:
        Updated AgentState with outputs and completed_tasks populated.

    Raises:
        ValueError: If the action on the current task is not recognised.
    """
    task   = _get_current_task(state)
    action = task.action

    handler = ACTION_MAP.get(action)
    if not handler:
        raise ValueError(
            f"recruitment_agent: unknown action '{action}'. "
            f"Valid actions: {list(ACTION_MAP.keys())}"
        )

    return handler(state)